version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache-gnuIDOR
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./gnuboard:/var/www/html
        ports:
            - 8000:80
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
    db:
        container_name : db1
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD : rootroot
            MYSQL_DATABASE : gnuIDOR
            MYSQL_USER : USER
            MYSQL_PASSWORD : USERUSER
        ports:
            - 9906:3306
        volumes:
            - ./php/db-init:/docker-entrypoint-initdb.d