services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: bash -c "
      python manage.py migrate &&
      echo 'from django.contrib.auth import get_user_model;
            User = get_user_model();
            User.objects.filter(username=\"root\").exists() or
            User.objects.create_superuser(\"root\", \"root@root.com\", \"rootpass\")'
      | python manage.py shell &&
      python manage.py runserver 0.0.0.0:8000"